Repository Kernel360/KBE5_HomeAid_BE, pull requests merged in 2025-07, with the labels that each got.

#152 [Feature] #148 서비스 이슈 CRUD 기능 추가
  global/src/main/java/com/homeaid/common/enumerate/DocumentType.java
  reservation/src/main/java/com/homeaid/controller/ServiceIssueController.java
  reservation/src/main/java/com/homeaid/domain/ServiceIssue.java
  reservation/src/main/java/com/homeaid/domain/ServiceIssueImage.java
  reservation/src/main/java/com/homeaid/dto/request/ServiceIssueRequestDto.java
  reservation/src/main/java/com/homeaid/dto/response/ServiceIssueResponseDto.java
  reservation/src/main/java/com/homeaid/exception/ReservationErrorCode.java
  reservation/src/main/java/com/homeaid/exception/ServiceIssueErrorCode.java
  reservation/src/main/java/com/homeaid/repository/ServiceIssueRepository.java
  reservation/src/main/java/com/homeaid/service/ReservationService.java
  reservation/src/main/java/com/homeaid/service/ReservationServiceImpl.java
  reservation/src/main/java/com/homeaid/service/ServiceIssueFileService.java
  reservation/src/main/java/com/homeaid/service/ServiceIssueFileServiceImpl.java
  reservation/src/main/java/com/homeaid/service/ServiceIssueService.java
  reservation/src/main/java/com/homeaid/service/ServiceIssueServiceImpl.java
  user/src/main/java/com/homeaid/security/config/SecurityConfig.java
Labels: feature

#154 [Refactor] #153 관리자 문의글 답변 수정/삭제 기능 수정
  admin/src/main/java/com/homeaid/boardreply/controller/AdminInquiryController.java
  admin/src/main/java/com/homeaid/boardreply/dto/response/InquiryWithReplyResponseDto.java
  admin/src/main/java/com/homeaid/boardreply/service/AdminInquiryService.java
  admin/src/main/java/com/homeaid/boardreply/service/AdminInquiryServiceImpl.java
  admin/src/main/java/com/homeaid/user/controller/AdminCustomerController.java
  admin/src/main/java/com/homeaid/user/dto/response/CustomerDetailResponseDto.java
  admin/src/main/java/com/homeaid/user/service/AdminCustomerService.java
  admin/src/main/java/com/homeaid/user/service/AdminCustomerServiceImpl.java
Labels: Refactor

#162 [Feature] 관리자 정산 스케줄링, 매니저 정산 상세페이지 추가
  admin/src/main/java/com/homeaid/dashboard/service/AdminDashboardServiceImpl.java
  admin/src/main/java/com/homeaid/payment/service/AdminPaymentServiceImpl.java
  admin/src/main/java/com/homeaid/settlement/controller/AdminSettlementController.java
  admin/src/main/java/com/homeaid/settlement/dto/SettlementWithManagerResponseDto.java
  admin/src/main/java/com/homeaid/settlement/scheduler/WeeklySettlementScheduler.java
  admin/src/main/java/com/homeaid/settlement/service/AdminSettlementService.java
  admin/src/main/java/com/homeaid/settlement/service/AdminSettlementServiceImpl.java
  admin/src/main/java/com/homeaid/settlement/validator/SettlementValidator.java
  admin/src/main/java/com/homeaid/statistics/service/AdminStatisticsServiceImpl.java
  payment/src/main/java/com/homeaid/payment/controller/PaymentController.java
  payment/src/main/java/com/homeaid/payment/dto/response/PaymentResponseDto.java
  payment/src/main/java/com/homeaid/payment/dto/response/ReservationPaymentDetailResponseDto.java
  payment/src/main/java/com/homeaid/payment/service/PaymentService.java
  payment/src/main/java/com/homeaid/payment/service/PaymentServiceImpl.java
  payment/src/main/java/com/homeaid/settlement/domain/Settlement.java
  payment/src/main/java/com/homeaid/settlement/domain/enumerate/SettlementStatus.java
  payment/src/main/java/com/homeaid/settlement/dto/response/SettlementResponseDto.java
  payment/src/main/java/com/homeaid/settlement/exception/SettlementErrorCode.java
  payment/src/main/java/com/homeaid/settlement/repository/SettlementRepository.java
  user/src/main/java/com/homeaid/dto/response/ManagerResponseDto.java
  user/src/main/java/com/homeaid/repository/ManagerRepository.java
  user/src/main/java/com/homeaid/service/ManagerService.java
  user/src/main/java/com/homeaid/service/ManagerServiceImpl.java
Labels: feature, Refactor

#169 [Feature] 관리자 환불 처리 기능 및 환불 내역 관리
  admin/src/main/java/com/homeaid/payment/controller/AdminPaymentController.java
  admin/src/main/java/com/homeaid/payment/controller/AdminRefundController.java
  admin/src/main/java/com/homeaid/payment/dto/RefundAdminDecisionRequestDto.java
  admin/src/main/java/com/homeaid/payment/service/AdminPaymentService.java
  admin/src/main/java/com/homeaid/payment/service/AdminPaymentServiceImpl.java
  admin/src/main/java/com/homeaid/payment/service/AdminRefundService.java
  admin/src/main/java/com/homeaid/payment/service/AdminRefundServiceImpl.java
  admin/src/main/java/com/homeaid/settlement/controller/AdminSettlementController.java
  admin/src/main/java/com/homeaid/settlement/scheduler/WeeklySettlementScheduler.java
  admin/src/main/java/com/homeaid/settlement/service/AdminSettlementService.java
  admin/src/main/java/com/homeaid/settlement/service/AdminSettlementServiceImpl.java
  global/src/main/java/com/homeaid/config/SwaggerConfig.java
  payment/src/main/java/com/homeaid/payment/controller/PaymentController.java
  payment/src/main/java/com/homeaid/payment/controller/RefundController.java
  payment/src/main/java/com/homeaid/payment/domain/Payment.java
  payment/src/main/java/com/homeaid/payment/domain/Refund.java
  payment/src/main/java/com/homeaid/payment/domain/enumerate/PaymentMethod.java
  payment/src/main/java/com/homeaid/payment/domain/enumerate/PaymentStatus.java
  payment/src/main/java/com/homeaid/payment/domain/enumerate/RefundReason.java
  payment/src/main/java/com/homeaid/payment/domain/enumerate/RefundStatus.java
  payment/src/main/java/com/homeaid/payment/domain/factory/RefundFactory.java
  payment/src/main/java/com/homeaid/payment/dto/request/PaymentRequestDto.java
  payment/src/main/java/com/homeaid/payment/dto/request/RefundRequestDto.java
  payment/src/main/java/com/homeaid/payment/dto/response/PaymentResponseDto.java
  payment/src/main/java/com/homeaid/payment/dto/response/RefundResponseDto.java
  payment/src/main/java/com/homeaid/payment/exception/PaymentErrorCode.java
  payment/src/main/java/com/homeaid/payment/exception/RefundErrorCode.java
  payment/src/main/java/com/homeaid/payment/policy/AfterCompletionPolicy.java
  payment/src/main/java/com/homeaid/payment/policy/Before7DaysPolicy.java
  payment/src/main/java/com/homeaid/payment/policy/Between3And7DaysPolicy.java
  payment/src/main/java/com/homeaid/payment/policy/LessThan3DaysPolicy.java
  payment/src/main/java/com/homeaid/payment/policy/RefundAmountPolicy.java
  payment/src/main/java/com/homeaid/payment/policy/RefundPolicyCalculator.java
  payment/src/main/java/com/homeaid/payment/repository/PaymentRepository.java
  payment/src/main/java/com/homeaid/payment/repository/RefundRepository.java
  payment/src/main/java/com/homeaid/payment/service/PaymentService.java
  payment/src/main/java/com/homeaid/payment/service/PaymentServiceImpl.java
  payment/src/main/java/com/homeaid/payment/service/RefundService.java
  payment/src/main/java/com/homeaid/payment/service/RefundServiceImpl.java
  payment/src/main/java/com/homeaid/payment/validator/RefundValidator.java
  payment/src/main/java/com/homeaid/settlement/controller/SettlementController.java
  payment/src/main/java/com/homeaid/settlement/dto/response/SettlementPaymentDetailResponseDto.java
  payment/src/main/java/com/homeaid/settlement/exception/SettlementErrorCode.java
  payment/src/main/java/com/homeaid/settlement/service/SettlementService.java
  payment/src/main/java/com/homeaid/settlement/service/SettlementServiceImpl.java
Labels: feature, Refactor

#174 [Feature] Google OAuth 로그인 기능 구현
  admin/src/main/java/com/homeaid/boardreply/controller/AdminInquiryController.java
  admin/src/main/java/com/homeaid/user/controller/AdminCustomerController.java
  board/src/main/java/com/homeaid/controller/UserBoardController.java
  global/src/main/java/com/homeaid/config/SwaggerConfig.java
  notification/src/main/java/com/homeaid/controller/NotificationController.java
  payment/src/main/java/com/homeaid/payment/controller/PaymentController.java
  payment/src/main/java/com/homeaid/payment/controller/RefundController.java
  payment/src/main/java/com/homeaid/settlement/controller/SettlementController.java
  reservation/src/main/java/com/homeaid/controller/MatchingController.java
  reservation/src/main/java/com/homeaid/controller/ReservationController.java
  reservation/src/main/java/com/homeaid/controller/ServiceIssueController.java
  review/src/main/java/com/homeaid/controller/ReviewController.java
  src/main/resources/application.yml
  user/build.gradle.kts
  user/src/main/java/com/homeaid/auth/controller/AuthController.java
  user/src/main/java/com/homeaid/auth/dto/request/AdditionalUserInfoDto.java
  user/src/main/java/com/homeaid/auth/dto/request/CustomerSignUpRequestDto.java
  user/src/main/java/com/homeaid/auth/dto/request/ManagerSignUpRequestDto.java
  user/src/main/java/com/homeaid/auth/dto/request/SignInRequestDto.java
  user/src/main/java/com/homeaid/auth/dto/response/OauthResponseDto.java
  user/src/main/java/com/homeaid/auth/dto/response/SignInResponseDto.java
  user/src/main/java/com/homeaid/auth/dto/response/SignUpResponseDto.java
  user/src/main/java/com/homeaid/auth/security/config/SecurityConfig.java
  user/src/main/java/com/homeaid/auth/security/filter/AccessTokenFilter.java
  user/src/main/java/com/homeaid/auth/security/filter/JwtAuthenticationFilter.java
  user/src/main/java/com/homeaid/auth/security/filter/OAuth2AuthenticationSuccessHandler.java
  user/src/main/java/com/homeaid/auth/security/jwt/JwtTokenProvider.java
  user/src/main/java/com/homeaid/auth/service/AuthService.java
  user/src/main/java/com/homeaid/auth/service/AuthServiceImpl.java
  user/src/main/java/com/homeaid/auth/service/CustomOAuth2UserService.java
  user/src/main/java/com/homeaid/auth/service/CustomUserDetailsService.java
  user/src/main/java/com/homeaid/auth/service/OAuthCodeService.java
  user/src/main/java/com/homeaid/auth/service/OAuthCodeServiceImpl.java
  user/src/main/java/com/homeaid/auth/user/CustomOAuth2User.java
  user/src/main/java/com/homeaid/auth/user/CustomUserDetails.java
  user/src/main/java/com/homeaid/auth/user/GoogleUserDetails.java
  user/src/main/java/com/homeaid/auth/user/OAuth2UserInfo.java
  user/src/main/java/com/homeaid/auth/util/CookieUtil.java
  user/src/main/java/com/homeaid/controller/CustomerController.java
  user/src/main/java/com/homeaid/controller/ManagerController.java
  user/src/main/java/com/homeaid/controller/SwaggerAuthController.java
  user/src/main/java/com/homeaid/controller/UserController.java
  user/src/main/java/com/homeaid/controller/UserWithdrawalController.java
  user/src/main/java/com/homeaid/domain/User.java
  user/src/main/java/com/homeaid/dto/response/CustomerResponseDto.java
  user/src/main/java/com/homeaid/repository/UserRepository.java
  user/src/main/java/com/homeaid/security/auth/controller/AuthController.java
  user/src/main/java/com/homeaid/security/auth/service/AuthService.java
  user/src/main/java/com/homeaid/service/UserService.java
  user/src/main/java/com/homeaid/service/UserServiceImpl.java
  worklog/src/main/java/com/homeaid/controller/WorkLogController.java
Labels: feature

#184 [Build] 로그 관리
  Jenkinsfile
  docker-compose.yml
  docker-compose/docker-compose.backend.yml
  docker-compose/docker-compose.infra.yml
  docker-compose/docker-compose.monitoring.yml
  docker-compose/docker-compose.yml
  src/main/resources/logback-spring.xml
Labels: Deploy

#186 Fix: docker-compose.backend.yml context, dockerfile 명시
  docker-compose/docker-compose.backend.yml
Labels: bugFix

#187 [Fix] docker-compose network 설정
  docker-compose/docker-compose.backend.yml
  docker-compose/docker-compose.infra.yml
  docker-compose/docker-compose.monitoring.yml
Labels: bugFix

#192 [refactor] console 로그 색상 추가
  docker-compose/docker-compose.monitoring.yml
  docker-compose/promtail-config.yml
  src/main/resources/logback-spring.xml
Labels: Deploy
