Repository Kernel360/KBE5_HomeAid_BE, pull requests merged in 2025-06, with the labels that each got.

#65 [Feature] #34 JWT 기반 로그인 기능 구현 및 Spring Security 적용
  user/build.gradle.kts
  user/src/main/java/com/homeaid/controller/UserController.java
  user/src/main/java/com/homeaid/domain/User.java
  user/src/main/java/com/homeaid/dto/request/CustomerSignUpRequestDto.java
  user/src/main/java/com/homeaid/dto/request/ManagerSignUpRequestDto.java
  user/src/main/java/com/homeaid/dto/request/UserSignInRequestDto.java
  user/src/main/java/com/homeaid/repository/UserRepository.java
  user/src/main/java/com/homeaid/security/CustomUserDetails.java
  user/src/main/java/com/homeaid/security/CustomUserDetailsService.java
  user/src/main/java/com/homeaid/security/JwtFilter.java
  user/src/main/java/com/homeaid/security/JwtUtil.java
  user/src/main/java/com/homeaid/security/SecurityConfig.java
  user/src/main/java/com/homeaid/security/SignInAuthenticationFilter.java
  user/src/main/java/com/homeaid/service/UserServiceImpl.java
Labels: feature

#63 매칭 기능 구현
  global/src/main/java/com/homeaid/config/SwaggerConfig.java
  reservation/build.gradle.kts
  reservation/src/main/java/com/homeaid/controller/MatchingController.java
  reservation/src/main/java/com/homeaid/domain/Matching.java
  reservation/src/main/java/com/homeaid/domain/Reservation.java
  reservation/src/main/java/com/homeaid/domain/enumerate/MatchingStatus.java
  reservation/src/main/java/com/homeaid/dto/request/CreateMatchingRequestDto.java
  reservation/src/main/java/com/homeaid/dto/request/MatchingCustomerResponseDto.java
  reservation/src/main/java/com/homeaid/dto/request/MatchingManagerResponseDto.java
  reservation/src/main/java/com/homeaid/dto/response/MatchingRecommendationResponseDto.java
  reservation/src/main/java/com/homeaid/exception/MatchingErrorCode.java
  reservation/src/main/java/com/homeaid/repository/MatchingRepository.java
  reservation/src/main/java/com/homeaid/service/MatchingService.java
  reservation/src/main/java/com/homeaid/service/MatchingServiceImpl.java
  reservation/src/test/java/com/homeaid/service/MatchingServiceTest.java
  reservation/src/test/java/com/homeaid/service/TestConfiguration.java
  reservation/src/test/resources/application-test.yml
  user/src/main/java/com/homeaid/domain/ManagerAvailability.java
  user/src/main/java/com/homeaid/domain/ManagerServiceOption.java
  user/src/main/java/com/homeaid/domain/User.java
  user/src/main/java/com/homeaid/domain/enumerate/Weekday.java
  user/src/main/java/com/homeaid/exception/UserErrorCode.java
  user/src/main/java/com/homeaid/repository/CustomerRepository.java
  user/src/main/java/com/homeaid/repository/ManagerRepository.java
Labels: feature

#66 Feature/#53 매니저 체크인 체크아웃 구현
  global/src/main/java/com/homeaid/config/SwaggerConfig.java
  reservation/src/main/java/com/homeaid/domain/Reservation.java
  worklog/build.gradle.kts
  worklog/src/main/java/com/homeaid/controller/WorkLogController.java
  worklog/src/main/java/com/homeaid/domain/WorkLog.java
  worklog/src/main/java/com/homeaid/domain/enumerate/WorkType.java
  worklog/src/main/java/com/homeaid/dto/request/CheckInRequestDto.java
  worklog/src/main/java/com/homeaid/dto/request/CheckOutRequestDto.java
  worklog/src/main/java/com/homeaid/dto/response/CheckInResponseDto.java
  worklog/src/main/java/com/homeaid/exception/WorkLogErrorCode.java
  worklog/src/main/java/com/homeaid/repository/WorkLogRepository.java
  worklog/src/main/java/com/homeaid/service/WorkLogService.java
  worklog/src/main/java/com/homeaid/service/WorkLogServiceImpl.java
  worklog/src/main/java/com/homeaid/util/GeoUtils.java
Labels: feature

#67 Feature/정산기능구현
  admin/build.gradle.kts
  admin/src/main/java/com/homeaid/serviceoption/controller/AdminSettlementController.java
  global/src/main/java/com/homeaid/config/web/WebConfig.java
  payment/build.gradle.kts
  payment/src/main/java/com/homeaid/controller/PaymentController.java
  payment/src/main/java/com/homeaid/controller/SettlementController.java
  payment/src/main/java/com/homeaid/domain/Payment.java
  payment/src/main/java/com/homeaid/domain/PaymentMethod.java
  payment/src/main/java/com/homeaid/domain/PaymentStatus.java
  payment/src/main/java/com/homeaid/domain/Settlement.java
  payment/src/main/java/com/homeaid/dto/request/PaymentRequestDto.java
  payment/src/main/java/com/homeaid/dto/request/SettlementRequestDto.java
  payment/src/main/java/com/homeaid/dto/response/PaymentResponseDto.java
  payment/src/main/java/com/homeaid/dto/response/SettlementResponseDto.java
  payment/src/main/java/com/homeaid/exception/PaymentErrorCode.java
  payment/src/main/java/com/homeaid/exception/SettlementErrorCode.java
  payment/src/main/java/com/homeaid/repository/PaymentRepository.java
  payment/src/main/java/com/homeaid/repository/SettlementRepository.java
  payment/src/main/java/com/homeaid/service/PaymentService.java
  payment/src/main/java/com/homeaid/service/PaymentServiceImpl.java
  payment/src/main/java/com/homeaid/service/SettlementService.java
  payment/src/main/java/com/homeaid/service/SettlementServiceImpl.java
  payment/src/test/java/com/homeaid/service/PaymentServiceImplTest.java
  payment/src/test/java/com/homeaid/service/SettlementServiceImplTest.java
  reservation/src/main/java/com/homeaid/domain/Reservation.java
  src/main/resources/application.yml
  user/src/main/java/com/homeaid/repository/ManagerRepository.java
Labels: feature

#75 [Feature] #70 사용자 통계 기능 구현
  global/src/main/java/com/homeaid/config/SwaggerConfig.java
  review/src/main/java/com/homeaid/controller/ReviewController.java
  review/src/main/java/com/homeaid/domain/Review.java
  review/src/main/java/com/homeaid/dto/request/CustomerReviewRequestDto.java
  review/src/main/java/com/homeaid/repository/ReviewRepository.java
  review/src/main/java/com/homeaid/service/ReviewServiceImpl.java
  review/src/main/java/com/homeaid/service/UserRatingUpdateService.java
  review/src/main/java/com/homeaid/service/UserRatingUpdateServiceImpl.java
  user/src/main/java/com/homeaid/domain/CustomerRating.java
  user/src/main/java/com/homeaid/domain/ManagerRating.java
  user/src/main/java/com/homeaid/repository/CustomerRatingRepository.java
  user/src/main/java/com/homeaid/repository/ManagerRatingRepository.java
Labels: feature

#81 RDS DB로 변환
  docker-compose.yml
Labels: Deploy

#87 API test 버그 수정 및 예약, 매칭 로그인 검증 추가
  global/src/main/java/com/homeaid/config/SwaggerConfig.java
  global/src/main/java/com/homeaid/exception/GlobalExceptionHandler.java
  reservation/src/main/java/com/homeaid/controller/MatchingController.java
  reservation/src/main/java/com/homeaid/controller/ReservationController.java
  reservation/src/main/java/com/homeaid/domain/Reservation.java
  reservation/src/main/java/com/homeaid/domain/ReservationItem.java
  reservation/src/main/java/com/homeaid/dto/request/MatchingCustomerResponseDto.java
  reservation/src/main/java/com/homeaid/dto/request/MatchingManagerResponseDto.java
  reservation/src/main/java/com/homeaid/dto/request/ReservationRequestDto.java
  reservation/src/main/java/com/homeaid/exception/ReservationErrorCode.java
  reservation/src/main/java/com/homeaid/service/MatchingService.java
  reservation/src/main/java/com/homeaid/service/MatchingServiceImpl.java
  reservation/src/main/java/com/homeaid/service/ReservationService.java
  reservation/src/main/java/com/homeaid/service/ReservationServiceImpl.java
  reservation/src/main/java/com/homeaid/validation/MatchingActionMemoRequest.java
  reservation/src/main/java/com/homeaid/validation/MatchingMemoConstraint.java
  reservation/src/main/java/com/homeaid/validation/MatchingMemoValidator.java
  reservation/src/test/java/com/homeaid/service/MatchingServiceTest.java
Labels: bugFix, Refactor

#89 도메인 조회 기능 추가
  board/src/main/java/com/homeaid/controller/UserBoardController.java
  board/src/main/java/com/homeaid/dto/response/PagedResponseDto.java
  board/src/main/java/com/homeaid/service/UserBoardService.java
  board/src/main/java/com/homeaid/service/UserBoardServiceImpl.java
  global/build.gradle.kts
  global/src/main/java/com/homeaid/common/response/PagedResponseDto.java
  global/src/main/java/com/homeaid/config/SwaggerConfig.java
  reservation/src/main/java/com/homeaid/controller/ReservationController.java
  reservation/src/main/java/com/homeaid/dto/response/MatchingResponseDto.java
  reservation/src/main/java/com/homeaid/repository/ReservationRepository.java
  reservation/src/main/java/com/homeaid/service/ReservationService.java
  reservation/src/main/java/com/homeaid/service/ReservationServiceImpl.java
  user/src/main/java/com/homeaid/controller/UserController.java
  worklog/build.gradle.kts
  worklog/src/main/java/com/homeaid/controller/WorkLogController.java
  worklog/src/main/java/com/homeaid/domain/WorkLog.java
  worklog/src/main/java/com/homeaid/dto/response/CheckInResponseDto.java
  worklog/src/main/java/com/homeaid/repository/WorkLogRepository.java
  worklog/src/main/java/com/homeaid/service/WorkLogService.java
  worklog/src/main/java/com/homeaid/service/WorkLogServiceImpl.java
Labels: feature

#91 매니저 상세정보 입력 기능 구현
  global/src/main/java/com/homeaid/config/SwaggerConfig.java
  global/src/main/java/com/homeaid/config/web/WebConfig.java
  user/src/main/java/com/homeaid/controller/ManagerController.java
  user/src/main/java/com/homeaid/domain/ManagerAvailability.java
  user/src/main/java/com/homeaid/dto/request/ManagerDetailInfoRequestDto.java
  user/src/main/java/com/homeaid/repository/ManagerAvailabilityRepository.java
  user/src/main/java/com/homeaid/repository/ManagerServiceOptionRepository.java
  user/src/main/java/com/homeaid/security/SecurityConfig.java
  user/src/main/java/com/homeaid/service/ManagerService.java
  user/src/main/java/com/homeaid/service/ManagerServiceImpl.java
  worklog/src/main/java/com/homeaid/controller/WorkLogController.java
Labels: feature

#94 [refactor] #34 LOGIN_FAILED에러 시 정확한 실패 사유 log 남기도록 수정
  user/src/main/java/com/homeaid/service/UserServiceImpl.java
Labels: Refactor

#97 관리자용 유저 목록 조회
  global/src/main/java/com/homeaid/config/SwaggerConfig.java
  user/src/main/java/com/homeaid/controller/CustomerController.java
  user/src/main/java/com/homeaid/controller/ManagerController.java
  user/src/main/java/com/homeaid/domain/Manager.java
  user/src/main/java/com/homeaid/domain/enumerate/ManagerStatus.java
  user/src/main/java/com/homeaid/dto/request/CustomerResponseDto.java
  user/src/main/java/com/homeaid/dto/request/StatusChangeRequest.java
  user/src/main/java/com/homeaid/dto/response/ManagerResponseDto.java
  user/src/main/java/com/homeaid/service/CustomerService.java
  user/src/main/java/com/homeaid/service/CustomerServiceImpl.java
  user/src/main/java/com/homeaid/service/ManagerService.java
  user/src/main/java/com/homeaid/service/ManagerServiceImpl.java
Labels: feature

#104 [Feat] 예약 requestDto 시간, 총액 추가 / 매칭 responseDto 매칭 상태 추가
  reservation/src/main/java/com/homeaid/controller/MatchingController.java
  reservation/src/main/java/com/homeaid/dto/request/ReservationRequestDto.java
  reservation/src/main/java/com/homeaid/dto/response/MatchingResponseDto.java
  reservation/src/main/java/com/homeaid/repository/MatchingRepository.java
  reservation/src/main/java/com/homeaid/service/MatchingService.java
  reservation/src/main/java/com/homeaid/service/MatchingServiceImpl.java
Labels: feature

#106 Feat/customer update
  user/src/main/java/com/homeaid/controller/UserController.java
  user/src/main/java/com/homeaid/domain/User.java
  user/src/main/java/com/homeaid/dto/request/UserUpdateRequestDto.java
  user/src/main/java/com/homeaid/service/UserService.java
  user/src/main/java/com/homeaid/service/UserServiceImpl.java
Labels: feature

#113 check in out 로직 수정
  worklog/src/main/java/com/homeaid/controller/WorkLogController.java
  worklog/src/main/java/com/homeaid/domain/WorkLog.java
  worklog/src/main/java/com/homeaid/dto/request/CheckInRequestDto.java
  worklog/src/main/java/com/homeaid/dto/request/CheckOutRequestDto.java
  worklog/src/main/java/com/homeaid/repository/WorkLogRepository.java
  worklog/src/main/java/com/homeaid/service/WorkLogService.java
  worklog/src/main/java/com/homeaid/service/WorkLogServiceImpl.java
Labels: Refactor

#120 서비스 옵션 통합 관리
  admin/src/main/java/com/homeaid/serviceoption/controller/ServiceOptionController.java
  admin/src/main/java/com/homeaid/serviceoption/dto/request/ServiceOptionRequestDto.java
  admin/src/main/java/com/homeaid/serviceoption/dto/request/ServiceSubOptionRequestDto.java
  admin/src/main/java/com/homeaid/serviceoption/dto/response/ServiceOptionDetailDto.java
  admin/src/main/java/com/homeaid/serviceoption/dto/response/ServiceOptionResponseDto.java
  admin/src/main/java/com/homeaid/serviceoption/dto/response/ServiceSubOptionResponseDto.java
  admin/src/main/java/com/homeaid/serviceoption/exception/ServiceOptionErrorCode.java
  admin/src/main/java/com/homeaid/serviceoption/service/ServiceOptionService.java
  admin/src/main/java/com/homeaid/serviceoption/service/ServiceOptionServiceImpl.java
  common-domain/build.gradle.kts
  common-domain/src/main/java/com/homeaid/serviceoption/converter/FeatureListConverter.java
  common-domain/src/main/java/com/homeaid/serviceoption/domain/ServiceOption.java
  common-domain/src/main/java/com/homeaid/serviceoption/domain/ServiceSubOption.java
  common-domain/src/main/java/com/homeaid/serviceoption/repository/ServiceSubOptionRepository.java
  global/src/main/java/com/homeaid/exception/GlobalExceptionHandler.java
  reservation/src/main/java/com/homeaid/controller/ReservationController.java
  reservation/src/main/java/com/homeaid/domain/Reservation.java
  reservation/src/main/java/com/homeaid/domain/ReservationItem.java
  reservation/src/main/java/com/homeaid/dto/request/ReservationRequestDto.java
  reservation/src/main/java/com/homeaid/dto/response/MatchingResponseDto.java
  reservation/src/main/java/com/homeaid/dto/response/ReservationResponseDto.java
  reservation/src/main/java/com/homeaid/service/MatchingServiceImpl.java
  reservation/src/main/java/com/homeaid/service/ReservationService.java
  reservation/src/main/java/com/homeaid/service/ReservationServiceImpl.java
  reservation/src/test/java/com/homeaid/service/MatchingServiceTest.java
  user/src/main/java/com/homeaid/repository/ManagerRepository.java
  user/src/main/java/com/homeaid/security/config/SecurityConfig.java
  user/src/main/java/com/homeaid/security/filter/AccessTokenFilter.java
Labels: Refactor

#118 [Feat] #117 Refresh Token을 Redis에 저장 및 관리하는 기능 구현
  build.gradle.kts
  global/src/main/java/com/homeaid/auth/dto/TokenResponse.java
  global/src/main/java/com/homeaid/auth/exception/TokenErrorCode.java
  global/src/main/java/com/homeaid/auth/service/RefreshTokenService.java
  global/src/main/java/com/homeaid/auth/service/TokenBlacklistService.java
  global/src/main/java/com/homeaid/config/RedisConfig.java
  global/src/main/java/com/homeaid/util/RedisKeyFactory.java
  global/src/main/java/com/homeaid/util/RedisUtil.java
  src/main/resources/application.yml
  user/src/main/java/com/homeaid/auth/controller/AuthController.java
  user/src/main/java/com/homeaid/auth/service/AuthService.java
  user/src/main/java/com/homeaid/security/config/SecurityConfig.java
  user/src/main/java/com/homeaid/security/filter/AccessTokenFilter.java
  user/src/main/java/com/homeaid/security/filter/JwtAuthenticationFilter.java
  user/src/main/java/com/homeaid/security/filter/RefreshTokenFilter.java
  user/src/main/java/com/homeaid/security/jwt/JwtTokenProvider.java
  user/src/main/java/com/homeaid/service/UserServiceImpl.java
Labels: feature, Refactor

#126 [Feature] 관리자 회원 전체 조회, 탈퇴 요청 조회 및 승인/거절 기능 구현
  admin/src/main/java/com/homeaid/payment/service/AdminPaymentServiceImpl.java
  admin/src/main/java/com/homeaid/settlement/service/AdminSettlementServiceImpl.java
  admin/src/main/java/com/homeaid/user/controller/AdminCustomerController.java
  admin/src/main/java/com/homeaid/user/controller/AdminManagerController.java
  admin/src/main/java/com/homeaid/user/controller/AdminWithdrawalRequestController.java
  admin/src/main/java/com/homeaid/user/dto/request/AdminCustomerSearchRequestDto.java
  admin/src/main/java/com/homeaid/user/dto/request/AdminDocumentReviewRequest.java
  admin/src/main/java/com/homeaid/user/dto/request/AdminManagerSearchRequestDto.java
  admin/src/main/java/com/homeaid/user/dto/request/AdminWithdrawalDecisionDto.java
  admin/src/main/java/com/homeaid/user/repository/AdminCustomerRepository.java
  admin/src/main/java/com/homeaid/user/repository/AdminManagerRepository.java
  admin/src/main/java/com/homeaid/user/repository/AdminWithdrawalRequestRepository.java
  admin/src/main/java/com/homeaid/user/service/AdminCustomerService.java
  admin/src/main/java/com/homeaid/user/service/AdminCustomerServiceImpl.java
  admin/src/main/java/com/homeaid/user/service/AdminManagerService.java
  admin/src/main/java/com/homeaid/user/service/AdminManagerServiceImpl.java
  admin/src/main/java/com/homeaid/user/service/AdminWithdrawalRequestService.java
  admin/src/main/java/com/homeaid/user/service/AdminWithdrawalRequestServiceImpl.java
  global/src/main/java/com/homeaid/config/SwaggerConfig.java
  payment/src/main/java/com/homeaid/payment/domain/Payment.java
  user/src/main/java/com/homeaid/controller/CustomerController.java
  user/src/main/java/com/homeaid/controller/ManagerController.java
  user/src/main/java/com/homeaid/controller/UserWithdrawalController.java
  user/src/main/java/com/homeaid/domain/CustomerAddress.java
  user/src/main/java/com/homeaid/domain/User.java
  user/src/main/java/com/homeaid/domain/UserWithdrawalRequest.java
  user/src/main/java/com/homeaid/domain/enumerate/RequestStatus.java
  user/src/main/java/com/homeaid/dto/request/UserWithdrawalRequestDto.java
  user/src/main/java/com/homeaid/dto/response/SimpleUserDto.java
  user/src/main/java/com/homeaid/dto/response/UserWithdrawalResponseDto.java
  user/src/main/java/com/homeaid/exception/WithdrawalErrorCode.java
  user/src/main/java/com/homeaid/repository/UserWithdrawalRequestRepository.java
  user/src/main/java/com/homeaid/service/CustomerService.java
  user/src/main/java/com/homeaid/service/CustomerServiceImpl.java
  user/src/main/java/com/homeaid/service/ManagerService.java
  user/src/main/java/com/homeaid/service/ManagerServiceImpl.java
  user/src/main/java/com/homeaid/service/UserWithdrawalRequestService.java
  user/src/main/java/com/homeaid/service/UserWithdrawalRequestServiceImpl.java
Labels: feature, Refactor

#128 매니저 상세 정보 입력 로직 수정
  admin/src/main/java/com/homeaid/serviceoption/dto/request/ServiceOptionRequestDto.java
  global/src/main/java/com/homeaid/util/RegionValidator.java
  global/src/main/resources/static/korea_sido_sgg.json
  user/src/main/java/com/homeaid/domain/ManagerAvailability.java
  user/src/main/java/com/homeaid/domain/ManagerPreferRegion.java
  user/src/main/java/com/homeaid/dto/request/ManagerAvailabilityRequestDto.java
  user/src/main/java/com/homeaid/dto/request/ManagerDetailInfoRequestDto.java
  user/src/main/java/com/homeaid/dto/request/ManagerPreferRegionRequest.java
  user/src/main/java/com/homeaid/exception/UserErrorCode.java
  user/src/main/java/com/homeaid/repository/ManagerPreferRegionRepository.java
  user/src/main/java/com/homeaid/service/ManagerServiceImpl.java
Labels: Refactor

#135 고객 주소록 변경 및 매칭 시스템 변경
  reservation/src/main/java/com/homeaid/dto/request/ReservationRequestDto.java
  reservation/src/main/java/com/homeaid/exception/ReservationErrorCode.java
  reservation/src/main/java/com/homeaid/service/MatchingServiceImpl.java
  reservation/src/test/java/com/homeaid/service/MatchingServiceTest.java
  user/src/main/java/com/homeaid/controller/CustomerController.java
  user/src/main/java/com/homeaid/domain/CustomerAddress.java
  user/src/main/java/com/homeaid/domain/Manager.java
  user/src/main/java/com/homeaid/dto/request/CustomerAddressSaveRequestDto.java
  user/src/main/java/com/homeaid/dto/request/CustomerAddressUpdateRequestDto.java
  user/src/main/java/com/homeaid/dto/response/CustomerAddressResponseDto.java
  user/src/main/java/com/homeaid/exception/UserErrorCode.java
  user/src/main/java/com/homeaid/repository/CustomerAddressRepository.java
  user/src/main/java/com/homeaid/repository/ManagerRepository.java
  user/src/main/java/com/homeaid/service/CustomerAddressService.java
  user/src/main/java/com/homeaid/service/CustomerAddressServiceImpl.java
Labels: Refactor

#136 Feat/관리자 통계 기능 추가
  admin/src/main/java/com/homeaid/statistics/controller/AdminStatisticsController.java
  admin/src/main/java/com/homeaid/statistics/dto/ManagerRatingStatsDto.java
  admin/src/main/java/com/homeaid/statistics/dto/MatchingStatsDto.java
  admin/src/main/java/com/homeaid/statistics/dto/PaymentStatsDto.java
  admin/src/main/java/com/homeaid/statistics/dto/ReservationStatsDto.java
  admin/src/main/java/com/homeaid/statistics/dto/SettlementStatsDto.java
  admin/src/main/java/com/homeaid/statistics/dto/UserStatsDto.java
  admin/src/main/java/com/homeaid/statistics/service/AdminStatisticsService.java
  admin/src/main/java/com/homeaid/statistics/service/AdminStatisticsServiceImpl.java
  payment/src/main/java/com/homeaid/payment/repository/PaymentRepository.java
  payment/src/main/java/com/homeaid/settlement/repository/SettlementRepository.java
  reservation/src/main/java/com/homeaid/repository/MatchingRepository.java
  reservation/src/main/java/com/homeaid/repository/ReservationRepository.java
  user/src/main/java/com/homeaid/repository/UserRepository.java
Labels: feature

#140 예약 전체 조회 수정
  global/src/main/java/com/homeaid/util/RegionValidator.java
  reservation/src/main/java/com/homeaid/service/MatchingServiceImpl.java
  reservation/src/test/java/com/homeaid/service/MatchingServiceTest.java
Labels: Refactor

#141 [Feature] 유저 회원 프로필 사진 등록 및 수정, 첨부파일 등록 조회, 리뷰 조회 수정
  global/build.gradle.kts
  global/src/main/java/com/homeaid/exception/ErrorCode.java
  global/src/main/java/com/homeaid/exception/GlobalExceptionHandler.java
  global/src/main/java/com/homeaid/util/FileValidator.java
  reservation/src/main/java/com/homeaid/controller/MatchingController.java
  review/src/main/java/com/homeaid/controller/ReviewController.java
  review/src/main/java/com/homeaid/dto/response/MyReviewResponseDto.java
  review/src/main/java/com/homeaid/dto/response/TargetReviewResponseDto.java
  review/src/main/java/com/homeaid/dto/response/WriterReviewResponseDto.java
  review/src/main/java/com/homeaid/repository/ReviewRepository.java
  review/src/main/java/com/homeaid/service/ReviewService.java
  review/src/main/java/com/homeaid/service/ReviewServiceImpl.java
  src/main/resources/application.yml
  user/build.gradle.kts
  user/src/main/java/com/homeaid/controller/ManagerController.java
  user/src/main/java/com/homeaid/controller/UserController.java
  user/src/main/java/com/homeaid/domain/Customer.java
  user/src/main/java/com/homeaid/domain/ManagerDocument.java
  user/src/main/java/com/homeaid/domain/User.java
  user/src/main/java/com/homeaid/dto/request/UserUpdateRequestDto.java
  user/src/main/java/com/homeaid/dto/response/ManagerDocumentDto.java
  user/src/main/java/com/homeaid/dto/response/ManagerDocumentListResponseDto.java
  user/src/main/java/com/homeaid/dto/response/SignUpResponseDto.java
  user/src/main/java/com/homeaid/dto/response/UserProfileResponseDto.java
  user/src/main/java/com/homeaid/security/auth/controller/AuthController.java
  user/src/main/java/com/homeaid/security/auth/service/AuthService.java
  user/src/main/java/com/homeaid/security/config/SecurityConfig.java
  user/src/main/java/com/homeaid/security/filter/JwtAuthenticationFilter.java
  user/src/main/java/com/homeaid/security/jwt/JwtTokenProvider.java
  user/src/main/java/com/homeaid/security/util/CookieUtil.java
  user/src/main/java/com/homeaid/service/ManagerService.java
  user/src/main/java/com/homeaid/service/ManagerServiceImpl.java
  user/src/main/java/com/homeaid/service/UserServiceImpl.java
Labels: feature, Refactor

#143 프론트 응답에 따른 예약 조회 수정
  reservation/src/main/java/com/homeaid/controller/ReservationController.java
  reservation/src/main/java/com/homeaid/dto/response/ReservationResponseDto.java
  reservation/src/main/java/com/homeaid/service/ReservationService.java
  reservation/src/main/java/com/homeaid/service/ReservationServiceImpl.java
  user/src/main/java/com/homeaid/security/config/SecurityConfig.java
Labels: Refactor

#145 [Feature] 문의글 조회 시 답변 조회 기능 추가
  admin/src/main/java/com/homeaid/boardreply/controller/AdminInquiryController.java
  admin/src/main/java/com/homeaid/boardreply/dto/request/BoardReplyCreateRequestDto.java
  admin/src/main/java/com/homeaid/boardreply/dto/request/BoardReplyUpdateRequestDto.java
  admin/src/main/java/com/homeaid/boardreply/dto/response/BoardReplyListResponseDto.java
  admin/src/main/java/com/homeaid/boardreply/dto/response/InquiryDetailResponseDto.java
  admin/src/main/java/com/homeaid/boardreply/repository/AdminBoardReplyRepository.java
  admin/src/main/java/com/homeaid/boardreply/service/AdminInquiryService.java
  admin/src/main/java/com/homeaid/boardreply/service/AdminInquiryServiceImpl.java
  board/src/main/java/com/homeaid/controller/UserBoardController.java
  board/src/main/java/com/homeaid/domain/BoardReply.java
  board/src/main/java/com/homeaid/domain/UserBoard.java
  board/src/main/java/com/homeaid/dto/response/UserBoardListResponseDto.java
  board/src/main/java/com/homeaid/dto/response/UserBoardResponseDto.java
  board/src/main/java/com/homeaid/repository/UserBoardRepository.java
  board/src/main/java/com/homeaid/service/UserBoardService.java
  board/src/main/java/com/homeaid/service/UserBoardServiceImpl.java
  common-domain/src/main/java/com/homeaid/serviceoption/domain/BoardReply.java
Labels: feature, Refactor

#151 [Feature] 관리자 매니저 상세조회후 서류 승인/거절
  admin/src/main/java/com/homeaid/payment/service/AdminPaymentServiceImpl.java
  admin/src/main/java/com/homeaid/user/controller/AdminCustomerController.java
  admin/src/main/java/com/homeaid/user/controller/AdminManagerController.java
  admin/src/main/java/com/homeaid/user/service/AdminManagerService.java
  admin/src/main/java/com/homeaid/user/service/AdminManagerServiceImpl.java
  payment/src/main/java/com/homeaid/payment/domain/Payment.java
  payment/src/main/java/com/homeaid/payment/service/PaymentServiceImpl.java
  payment/src/main/java/com/homeaid/payment/validator/PaymentValidator.java
  user/src/main/java/com/homeaid/domain/Manager.java
  user/src/main/java/com/homeaid/domain/enumerate/ManagerStatus.java
  user/src/main/java/com/homeaid/dto/response/ManagerResponseDto.java
  user/src/main/java/com/homeaid/exception/UserErrorCode.java
Labels: feature, Refactor
